config/routes.rb
Rails.application.routes.draw do

  resources :clients
  get 'clients/:id/enabled' => 'clients#enabled', :as => :client_enabled

  devise_for :users


  as :user do
    get 'users' => 'users#index'
    get 'users/new' => 'users#new'
    post 'users' => 'users#create'
  end

  get 'users/:id/enabled' => 'users#enabled', :as => :user_enabled

  get 'users/:id', :to => 'users#show', :as => :user
  get 'users/:id/edit' => 'users#edit', :as => :edit_user
  
  put 'users/:id' => 'users#update'
  patch 'users/:id' => 'users#update'


  get 'users/:id/edit_password' => 'users#edit_password', :as => :edit_password_user
  
  put 'users/:id/update_password' => 'users#update_password'
  patch 'users/:id/update_password' => 'users#update_password'

  root 'home#index'
  
end

app/models/client.rb
class Client < ActiveRecord::Base

	attr_accessible :nome, :advogado, :razaosocial, :endereco, :numero, :bairro, :cidade, :uf, :complemento, 
					:contato, :cpfcnpj, :email, :obs, :enabled, :tel1, :tel2
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registrable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :nome, :email, :telefone, :password, :password_confirmation, :enabled

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #helper_method :resource, :resource_name, :devise_mapping

  before_action :authenticate_user!

  protected

  def layout_by_resource
  	if devise_controller?
  		"devise"
  	else
  		"application"
  	end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Cliente apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def enabled
    @client = Client.find(params[:id])

    if @client.enabled ==  false
      @client.update_attribute(:enabled,true) 
    else
      @client.update_attribute(:enabled,false) 
    end

    redirect_to clients_path, notice: 'Alterado status do cliente!'
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:nome, :advogado, :razaosocial, :endereco, :numero, :bairro, :cidade, :uf, :complemento, 
          :contato, :cpfcnpj, :email, :obs, :enabled, :tel1, :tel2)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!

	def index

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end	

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to @user, 
			  notice: 'Usuario editado com sucesso!'
		else
			render action: :edit
		end
	end

	def create
		@user = User.new(params[:user])

		if @user.save
			redirect_to @user, notice: 'Cadastro realizado com sucesso!'
		else
			render action: :new
		end
	end

	def edit_password
		@user = User.find(params[:id])
	end

	def update_password
		@user = User.find(current_user.id)
		
		if @user.update(user_params)
		    # Sign in the user by passing validation in case his password changed
		    sign_in @user, :bypass => true
		    redirect_to root_path, notice: 'Senha alterada com sucesso.'
	  	else
	  		render action: :edit_password, alert: 'Senha nao alterada. Tente novamente.'
	  	end
	end

	def enabled
		@user = User.find(params[:id])

		if @user.enabled ==  false
			@user.update_attribute(:enabled,true) 
		else
			@user.update_attribute(:enabled,false) 
		end

		redirect_to users_path, notice: 'Alterado status do usuario!'
		
	end

private

	def user_params
		params.
		require(:user).
		permit(:email, :nome, :telefone, :password, :password_confirmation, :enabled)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">

  <%= f.label :nome %>
  <%= f.text_field :nome, class: 'form-control' %>

  <%= f.label :razaosocial %>
  <%= f.text_field :razaosocial, class: 'form-control' %>

  <%= f.label :endereco %>
  <%= f.text_field :endereco, class: 'form-control' %>

  <%= f.label :numero %>
  <%= f.text_field :numero, class: 'form-control' %>

  <%= f.label :complemento %>
  <%= f.text_field :complemento, class: 'form-control' %>

  <%= f.label :bairro %>
  <%= f.text_field :bairro, class: 'form-control' %>

  <%= f.label :cidade %>
  <%= f.text_field :cidade, class: 'form-control' %>

  <%= f.label :uf %>
  <%= f.text_field :uf, class: 'form-control' %>

  <%= f.label :advogado %>
  <%= f.text_field :advogado, class: 'form-control' %>

  <%= f.label :contato %>
  <%= f.text_field :contato, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>

  <%= f.label :tel1 %>
  <%= f.text_field :tel1, class: 'form-control' %>

  <%= f.label :tel2 %>
  <%= f.text_field :tel2, class: 'form-control' %>

  <%= f.label :obs %>
  <%= f.text_area :obs, class: 'form-control' %>

  <p></p>
  <%= f.submit "Salvar", class: 'form-group' %>

</div>

<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Ver', @client %> |
<%= link_to 'Voltar', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th>Contato</th>
      <th>Telefone</th>
      <th>Advogado</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.nome %></td>
        <td><%= client.email %></td>
        <td><%= client.contato %></td>
        <td><%= client.tel1 %> - <%= client.tel2 %></td>
        <td><%= client.advogado %></td>
        <td><td><%= link_to "#{client.enabled}", client_enabled_path(client.id) %></td></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

<div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             Advanced Tables
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Rendering engine</th>
                                            <th>Browser</th>
                                            <th>Platform(s)</th>
                                            <th>Engine version</th>
                                            <th>CSS grade</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="odd gradeX">
                                            <td>Trident</td>
                                            <td>Internet Explorer 4.0</td>
                                            <td>Win 95+</td>
                                            <td class="center">4</td>
                                            <td class="center">X</td>
                                        </tr>
                                        <tr class="even gradeC">
                                            <td>Trident</td>
                                            <td>Internet Explorer 5.0</td>
                                            <td>Win 95+</td>
                                            <td class="center">5</td>
                                            <td class="center">C</td>
                                        </tr>
                                        <tr class="gradeA">
                                            <td>Misc</td>
                                            <td>NetFront 3.4</td>
                                            <td>Embedded devices</td>
                                            <td class="center">-</td>
                                            <td class="center">A</td>
                                        </tr>
                                        <tr class="gradeU">
                                            <td>Other browsers</td>
                                            <td>All others</td>
                                            <td>-</td>
                                            <td class="center">-</td>
                                            <td class="center">U</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>

app/views/clients/new.html.erb
<h1>Cadastro de cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
	<div class="panel-heading">
		<strong>Cliente</strong> >> <%= @client.id %> 
	</div>
	<div class="panel-body">
		<strong>Nome: </strong><%= @client.nome %> <br>
		<strong>Razão Social: </strong><%= @client.razaosocial %> <br>
		<strong>Endereço: </strong><%= @client.endereco %>, <%= @client.numero %> <br>
		<strong>Complemento: </strong><%= @client.complemento %>  <strong>Bairro: </strong><%= @client.bairro %> <br>
		<strong>Cidade: </strong><%= @client.cidade %>-<% @client.uf %><br>
		<strong>Contato:</strong><%= @client.contato %>  <strong>Advogado:</strong><%= @client.advogado %> <br>
		<strong>E-mail:</strong><%= @client.email %>  <strong>Telefones:</strong><%= @client.tel1 %> / <%= @client.tel2 %>

	</div>
</div>

<%= link_to 'Editar', edit_client_path(@client) %> |
<%= link_to 'Voltar', clients_path %>

app/views/home/index.html.erb
<h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa nam temporibus quod sapiente, qui, dolorem nulla, pariatur consequatur distinctio incidunt sit obcaecati! Exercitationem possimus, dolor illum maxime. Asperiores, harum deleniti.</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>BBC advogados</title>
 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Binary admin</a> 
            </div>
  			<div style="color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;"> 
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><% if user_signed_in? %><strong><%= current_user.email %></strong> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Meu Perfil", current_user %></li>
                    <li><%= link_to "Alterar senha", edit_password_user_path(current_user.id) %></li>
                </ul>
                </li>
                   				
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-danger square-btn-adjust'  %> <% end %>
  			</div>
        </nav>   
           <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
				<li class="text-center">
                    <img src="find_user.png" class="user-image img-responsive"/>
					</li>
				
					
                    <li>
                        <a  href="index.html"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                      <li>
                        <a  href="ui.html"><i class="fa fa-desktop fa-3x"></i> UI Elements</a>
                    </li>
                    <li>
                        <a  href="tab-panel.html"><i class="fa fa-qrcode fa-3x"></i> Tabs & Panels</a>
                    </li>
						   <li  >
                        <a  href="chart.html"><i class="fa fa-bar-chart-o fa-3x"></i> Morris Charts</a>
                    </li>	
                      <li  >
                        <a  href="table.html"><i class="fa fa-table fa-3x"></i> Table Examples</a>
                    </li>
                    <li  >
                        <a  href="form.html"><i class="fa fa-edit fa-3x"></i> Forms </a>
                    </li>				
					
					                   
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-3x"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>

                                </ul>
                               
                            </li>
                        </ul>
                      </li>  
                  <li  >
                        <a class="active-menu"  href="blank.html"><i class="fa fa-square-o fa-3x"></i> Blank Page</a>
                    </li>	
                </ul>
               
            </div>
            
        </nav>  
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                      <div id="error_explanation">
                        <% if notice %>
                        <p class="alert alert-success"><%= notice %>
                          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                        </p>
                        <% end %>
                        <% if alert %>
                        <p class="alert alert-danger"><%= alert %>
                          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                        </p>
                        <% end %>
                      </div>

                      	<%= yield %>
                        
                    </div>
                </div>
                 <!-- /. ROW  -->
                 <hr />
               
    </div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
        </div>
  <script>
  $(document).ready(function () {
    $('#dataTables-example').dataTable();
  });
</script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>Login::BBC Advogados</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<%= yield(:head) %>

</head>
<body>

	<div class="col-lg-5 col-lg-offset-4">
		<div class="panel panel-default" id="form">
			<div class="panel-heading panel-login">
				<h3 class="panel-title">Login :: BBC Advogados</h3>
			</div>
			<div class="panel-body">
				<%= yield %>
			</div>
		</div>
		
	</div>
	<div id="error_explanation">
		<% if notice %>
	  		<p class="alert alert-success"><%= notice %>
	  			<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
	  		</p>
		<% end %>
		<% if alert %>
	  		<p class="alert alert-danger"><%= alert %>
	  			<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
	  		</p>
		<% end %>
	</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, html: {role: "form"} do |f| %>

<div class="form-group">

	<%= f.label :nome %>
	<%= f.text_field :nome, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.text_field :email, class: 'form-control' %>

	<%= f.label :telefone %>
	<%= f.text_field :telefone, class: 'form-control' %>

	<p></p>
	<%= f.submit "Salvar", class: 'form-group' %>

</div>

<% end %>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form' %>

<%= link_to 'Ver', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/edit_password.html.erb
<h2>Altere a sua senha</h2>

<%= form_for @user, url: "update_password", html: {role: "form"} do |f| %>

  <div class="form-group">

	<%= f.label :password, "Senha" %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, "Confirme a senha" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<p></p>
	<%= f.submit "Alterar senha", class: 'form-group' %>

  </div>

<% end %>

app/views/users/index.html.erb
<h2>Listagem de Usuários</h2>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th>Telefone</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% for user in @users %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= user.email %></td>
        <td><%= user.telefone %></td>
        <td><%= link_to "#{user.enabled}", user_enabled_path(user.id) %></td>
        <td><%= link_to 'Ver', user %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h2>Cadastro de Usuários</h2>

<%= form_for @user, html: {role: "form"} do |f| %>

<div class="form-group">

	<%= f.label :nome %>
	<%= f.text_field :nome, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.text_field :email, class: 'form-control' %>

	<%= f.label :telefone %>
	<%= f.text_field :telefone, class: 'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<p></p>
	<%= f.submit "Salvar", class: 'form-group' %>

</div>

<% end %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>

<p>
	<strong>Telefone:</strong>
	<%= @user.telefone %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>